---
repo_os_family: "centos{{ ansible_distribution_major_version }}"
baseurl_os_family: "redhat{{ ansible_distribution_major_version }}"

hdp_main_repo_url: "{{ repo_base_url }}/HDP/{{ repo_os_family }}/{{ hdp_version }}-{{ hdp_build_number_repo }}"
hdf_main_repo_url: "{{ repo_base_url }}/HDF/{{ repo_os_family }}/{{ hdf_version }}-{{ hdp_build_number_repo }}"
hdpsearch_main_repo_url: "{{ repo_base_url }}/HDP-SOLR-{{ hdpsearch_version }}-{{ hdpsearch_build_number }}/repos/{{ repo_os_family }}"
main_os_target: "operating_systems/{{ baseurl_os_family }}"

gpl_repo_url: "{{ repo_base_url }}/HDP-GPL/{{ repo_os_family }}/{{ hdp_version }}-{{ hdp_build_number_repo }}"

utils_repo_url: "{{ repo_base_url }}/HDP-UTILS-{{ utils_version }}/repos/{{ repo_os_family }}"
utils_os_target: "operating_systems/{{ baseurl_os_family }}/repositories/HDP-UTILS-{{ utils_version }}"
