---
postgres_port: 5432
mysql_port: 3306

#################################
## dynamic blueprint variables ##
#################################
registry_dns_bind_port: '53'

########################
## path configuration ##
########################
# Common base dirs
base_log_dir:     "/var/log"
base_metrics_dir: "/var/lib"
base_tmp_dir:     "/tmp"

# Specific base data dirs
hadoop_base_dir:        "/hadoop"
kafka_base_dir:         "/kafka-logs"
nifi_base_dir:          "/var/lib/nifi"
nifi_registry_base_dir: "/var/lib/nifi-registry"


# HDFS dirs
hdfs_dfs_namenode_checkpoint_dir: "{{ hadoop_base_dir }}/hdfs/namesecondary"
hdfs_dfs_namenode_name_dir: "{{ hadoop_base_dir }}/hdfs/namenode"
hdfs_dfs_journalnode_edits_dir: "{{ hadoop_base_dir }}/hdfs/journalnode"
hdfs_dfs_datanode_data_dir: "{{ hadoop_base_dir }}/hdfs/data"
hdfs_log_dir_prefix: "{{ base_log_dir }}/hadoop"

# Yarn dirs
yarn_nodemanager_local_dirs: "{{ hadoop_base_dir }}/yarn/local"
yarn_nodemanager_log_dirs: "{{ hadoop_base_dir }}/yarn/log"
yarn_timeline_service_leveldb_state_store_path: "{{ hadoop_base_dir }}/yarn/timeline"
yarn_timeline_service_leveldb_timeline_store_path: "{{ hadoop_base_dir }}/yarn/timeline"
yarn_log_dir_prefix: "{{ base_log_dir }}/hadoop-yarn"

# Mapreduce dirs
mapreduce_jobhistory_recovery_store_leveldb_path: "{{ hadoop_base_dir }}/mapreduce/jhs"
mapred_log_dir_prefix: "{{ base_log_dir }}/hadoop-mapreduce"

# Zookeeper dirs
zookeeper_data_dir: "{{ hadoop_base_dir }}/zookeeper"
zookeeper_log_dir: "{{ base_log_dir }}/zookeeper"

# Kafka dirs
kafka_log_dir: "{{ base_log_dir }}/kafka"
kafka_broker_log_dirs: "{{ kafka_base_dir }}"

# Oozie dirs
oozie_data_dir: "{{ hadoop_base_dir }}/oozie/data"
oozie_log_dir: "{{ base_log_dir }}/oozie"

# Storm dirs
storm_local_dir: "{{ hadoop_base_dir }}/storm"
storm_log_dir: "{{ base_log_dir }}/storm"

# Infra-Solr dirs
infra_solr_datadir: "{{ hadoop_base_dir }}/ambari-infra-solr/data"
infra_solr_log_dir: "{{ base_log_dir }}/ambari-infra-solr"

## Ranger audit (spool log) dirs
ranger_yarn_xasecure_audit_destination_hdfs_batch_filespool_dir: "{{ base_log_dir }}/hadoop/yarn/audit/hdfs/spool"
ranger_yarn_xasecure_audit_destination_solr_batch_filespool_dir: "{{ base_log_dir }}/hadoop/yarn/audit/solr/spool"
ranger_kafka_xasecure_audit_destination_hdfs_batch_filespool_dir: "{{ base_log_dir }}/kafka/audit/hdfs/spool"
ranger_kafka_xasecure_audit_destination_solr_batch_filespool_dir: "{{ base_log_dir }}/kafka/audit/solr/spool"
ranger_storm_xasecure_audit_destination_hdfs_batch_filespool_dir: "{{ base_log_dir }}/storm/audit/hdfs/spool"
ranger_storm_xasecure_audit_destination_solr_batch_filespool_dir: "{{ base_log_dir }}/storm/audit/solr/spool"

# NIFI Dirs
nifi_internal_dir: "{{ nifi_base_dir }}"
nifi_content_repository_dir_default: "{{ nifi_base_dir }}/content_repository"
nifi_database_dir: "{{ nifi_base_dir }}/database_repository"
nifi_flowfile_repository_dir: "{{ nifi_base_dir }}/flowfile_repository"
nifi_provenance_repository_dir_default: "{{ nifi_base_dir }}/provenance_repository"
nifi_node_log_dir: "{{ base_log_dir }}/nifi"

## NIFI-Registry Dirs
nifi_registry_internal_dir: "{{ nifi_registry_base_dir }}"
nifi_registry_database_dir: "{{ nifi_registry_base_dir }}/database"
nifi_registry_internal_config_dir: "{{ nifi_registry_base_dir }}/conf"
nifi_registry_log_dir: "{{ base_log_dir }}/nifi-registry"

# Other dirs
hive_druid_working_directory: "{{ base_tmp_dir }}/druid-indexing"
