---

#- name: Deploy HTTPD REPO
#  hosts: ambari-server
#  any_errors_fatal: true
#  become: yes
#  roles:
#    - offline_repo

- hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  vars_files: 
    - ./roles/offline_repo/defaults/main.yml 
  tasks: 
    - name: Install lib Python
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "libselinux-python"

    - name: Deploy Ambari Repo Files
      template: 
         src: ./roles/offline_repo/templates/ambari.repo 
         dest: "/etc/yum.repos.d/ambari.repo"

    - name: print install_hdf
      debug:
        msg: "{{ install_hdf }}"

    - name: Deploy HDF Repo Files
      template:
         src: ./roles/offline_repo/templates/hdf.repo
         dest: "/etc/yum.repos.d/hdf.repo"
      when: install_hdf is defined and install_hdf

    - block:
        - name: Deploy HDP Repo Files
          template:
             src: ./roles/offline_repo/templates/hdp.repo
             dest: "/etc/yum.repos.d/hdp.repo"

        - name: Deploy HDP-GPL Repo Files
          template:
             src: ./roles/offline_repo/templates/hdp.gpl.repo
             dest: "/etc/yum.repos.d/hdp.gpl.repo"
      when: install_hdp is defined and install_hdp
